services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - REACT_APP_VERSION=${REACT_APP_VERSION}
      - REACT_APP_API=${REACT_APP_API}
